git clone https://github.com/Qbicz/SG-command-recognition
git clone https://github.com/FragJage/SpeakerVoiceIdentifier
git clone https://github.com/VasuGoel/smart-home-automation-system.git
git clone https://github.com/Malayanil/VoiceRecognition-Arduino.git
git clone https://github.com/Sinketsu/SmartHomeSpeechOnDelphi.git
git clone https://github.com/NisaarAgharia/home.AI
git clone https://github.com/pcNewbee/SmartHome.git
git clone https://github.com/devancakra/Arduino-Mega-based-Smart-Home-Control-with-Voice-Instruction-via-Bluetooth.git
git clone https://github.com/elechouse/VoiceRecognitionV3.git
git clone https://github.com/AhmedTarekkk/Smart-Home-Controlled-By-Voice.git
git clone https://github.com/imchayan1999/Protect-Your-Home-.git
git clone https://github.com/brain-factory-etti/face-recognition-app.git
git clone https://github.com/MarcoLuw/smart-home.git
git clone https://github.com/akstron/Smart-Home-Challenge.git
git clone https://github.com/segdavids/Smart_Home-VisitorDetectionApp.git
git clone https://github.com/webstorage119/AI_project.git
git clone https://github.com/AnasNaz/Smart-Burglar-Alarm-Project.git
git clone https://github.com/gurdasanivishal/final_year_project.git
git clone https://github.com/Sam2621/House_Security.git
git clone https://github.com/nikhil-js/Smart-Home-using-Hand-Gesture-Technology.git
git clone https://github.com/Raebal/Face_recognition.git